### ISSUE TITLE
[BUG] Armour Statues v2.9.4 fails to load on Spigot 1.20.2

### ISSUE THREAD

**Issue by thisisthedogtor** [MukiTanuki/armor-statues#23]
#### Issue Description:

Whenever I try to load the pack on my Spigot 1.20.2 server, I receive an error message in the console, and the server shuts down again.

#### What happens:
```
 [21:06:52] [ServerMain/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Multiple entries with same key: LootItemConditionRandomChance[probability=0.15]=armor_statues:random_chance_10 and LootItemConditionRandomChance[probability=0.15]=armor_statues:random_chance_15
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:249) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at org.bukkit.craftbukkit.Main.main(Main.java:225) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at org.bukkit.craftbukkit.bootstrap.Main.lambda$1(Main.java:60) ~[craftbukkit.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: LootItemConditionRandomChance[probability=0.15]=armor_statues:random_chance_10 and LootItemConditionRandomChance[probability=0.15]=armor_statues:random_chance_15
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:378) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:372) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:246) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:133) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:572) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:600) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:587) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.world.level.storage.loot.LootDataManager.a(LootDataManager.java:106) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.world.level.storage.loot.LootDataManager.lambda$3(LootDataManager.java:49) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.Reloadable.a(SourceFile:69) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.SystemUtils.a(SourceFile:951) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.SystemUtils.c(SourceFile:939) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.Main.main(Main.java:217) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	... 3 more
```

#### What you expected to happen:

The server loads the datapack without a problem

#### Steps to reproduce:

1. Put the world into the datapack folder on the server
2. Try to start the server

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.20.2
- Armor Statues: v2.9.4

- Server: Spigot 1.20.2-R0.1-SNAPSHOT

**Comment by MukiTanuki** [comment]
v2.9.4 is outdated, but even so this should probably be a bug report for spigot, not armor statues.
